apiVersion: apps/v1
kind: Deployment

metadata:
  name: deployment-mongo
  labels:
    something: mongo-tunglt
spec:
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: mongo-tunglt

  template:
    metadata:
      name: demo-mongo-pod
      labels:
        app: mongo-tunglt
    spec:
      containers:
        - name: mongo-nodea
          image: mongo
          ports:
            - containerPort: 27017
